// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMShooting","status":true,"description":"プレイヤーとイベントに弾を発射する機能を追加します。","parameters":{"shotKey":"A","holdKey":"D","holdType":"HOLD","deadSwitch":"A","resetDeadSwitch":"true","leaderShotSe":"Shot1","leaderShotSeParam":"{\"volume\":70, \"pitch\":150, \"pan\":0}","defaultDeadAnimeId":"67","playerDeadEventId":"0","useGameover":"true","maxPlayerBullet":"128","maxEnemyBullet":"128","bulletSizeTable":"6,14,6,6,6,6,6,6","bulletBlendTable":"0,0,0,0,0,0,0,0","equipDummyX":"408","equipDummyY":"312","useLevelUpMessage":"true","padButtons":"ok,cancel,menu,shift,shot,hold,pageup,pagedown","padButtonNames":"決定,キャンセル,メニュー,ダッシュ,ショット,向き固定,キャラ変更(前),キャラ変更(次)","defaultPadButtons":"cancel,ok,shift,menu,pageup,pagedown,hold,shot,hold,shot,hold,shot","padConfigCommand":"パッドボタン配置"}}
];
